add : 로직 추가
givinkwon/baseball pull request #2
Opened 2022-04-26 04:12 UTC by givinkwon

2022-04-26 08:46 UTC, JoyDaheeCha requested changes
기빈님 안녕하세요. 꼼꼼하게 잘 작업하셨네요. 

한번에 코멘트를 너무 많이 드리면 부담스러우실 듯 하여, 1차 리뷰 먼저 드립니다. :) 
수정후 다시 PR 요청 주시고, slack으로 알려주세요 (제가 메일을 자주 놓쳐서요 ㅠㅠ )

고생하셨습니다. 
+ 커밋 단위에 대해 허들로 질문주셔서, 예시 전달드려요. (아래 참고)

## 1) 커밋은 기능 단위로 분리해주세요. 
![image](https://user-images.githubusercontent.com/56214102/165251789-c2e2fa15-2fdb-4131-bc06-f1cd5ea02545.png)
과제 문서에 예시가 없어서 위 요구사항이 애매했을 듯 해요. 

아래 예시 참고해주세요. (어디까지나 예시이며, 답은 아닙니다 😄 )
- 요구사항: 사칙연산 계산기를 구현하라
- README.md 내 체크 리스트 를 만든다.
![image](https://user-images.githubusercontent.com/56214102/165252120-85778130-005b-4c5b-9728-aea8e7a127a6.png)
- 커밋 분리 예시
![image](https://user-images.githubusercontent.com/56214102/165252465-e387186a-d9e0-4b75-9437-968312bad917.png)

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/test/java/gibin/kwon/study/StduyTest.java
> +//        assertThat(result).containsExactly(String.valueOf(goal));
사용하지 않는 주석은 제거하는 것이 어떨까요?

만약 원복을 위해 남겨두신거라면, // TODO: 이유
의 형태로 남겨, 다른 개발자들이 한 눈에 알아 볼 수 있도록 해주시면 좋을 듯 합니다. 

레퍼런스: 클린코드 주석 
https://nesoy.github.io/articles/2018-01/CleanCode-Comment

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/test/java/gibin/kwon/study/StduyTest.java
> +    @DisplayName("splitTest")
본 테스트 코드는 간단해서 충분히 알아볼 수 있지만, 
추후 숫자야구게임의 테스트 코드 개발시 DisplayName을 적어주면 StudyTest 클래스 내 주요 메서드가 무엇이 있는지 빠르게 파악 할 수 있을 듯합니다.  

레퍼런스: 테스트코드 예쁘게 작성하기
https://velog.io/@tonic523/junit5-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%9D%B4%EC%81%98%EA%B2%8C-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/test/java/gibin/kwon/study/StduyTest.java
> +        assertThat(result.equals(goal));
string의 equals 메서드를 사용하셨군요! 깔끔하게 잘 적으셨습니다. 

제안: assertJ의 isEqualTo 메서드 사용은 어떨까요?

이유: 잘 알려진 isEqualTo를 사용하면, "a,b가 같음을 테스트하는 것이 테스트의 목적이구나"라고 타 개발자가 빠르게 이해할 수 있습니다. 

레퍼런스: AssertJ 필수 부분 정리
https://pjh3749.tistory.com/241

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/test/java/gibin/kwon/study/StduyTest.java
> +        }).isInstanceOf(StringIndexOutOfBoundsException.class);
정상 동작과 예외 동작을 하나의 테스트 코드에서 확인하고 있습니다. 

하나의 테스트 코드에서는 가능한 한 개의 기능만 확인하는 건 어떨꺼요?

예. 
테스트1: charAt은 Index의 알파벳을 반환한다. 
테스트2: 문자열길이-1을 CharAt의 인덱스로 넣으면 예외가 발생한다.

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/test/java/gibin/kwon/study/StduyTest.java
> +    //@CsvSource(value = {"1: true", "2: true", "3 : true", "4:false","5:false"}, delimiter = ':')
ParameterizedTest 사용 어려웠을텐데 잘 쓰셨어요! 👍 
true, false를 valueSource로 처리하지않은 이유가 있을까요?

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/Stduy.java
> +}
요 클래스는 무슨 일을 하나요?

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/baseballgame/controller/Controller.java
> +public class Controller {
nit: MVC 구조를 회사 프로젝트에서 보셔서, 네이밍을 Controller로 정하신걸까요?

MVC 구조가 아닌데 Controller 네이밍을 사용하면 오히려 혼란을 줄 수 있을 것 같아요.

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/StudyApplication.java
> +@SpringBootApplication
nit: 이 프로젝트를 springBoot로 띄우신 이유가 있을까요?

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/baseballgame/service/BaseBallGameService.java
> +    final int END_NUMBER = 9;
상수네요. 대문자 사용 잘 하셨습니다. 다만, 상수면 static 키워드가 들어가야하지 않을까요?

아래 내용 공부해보심 좋을 듯 합니다. 
1) static 사용 이유
2) private 변수는 언제 쓰는지 => public / protected / default / private 비교

Tip: 혹시 상수 선언시, final static 선언 순서가 헷갈리신다면, psfi 단축어를 intelliJ에서 지원합니다. 
psfi = private static final int

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/baseballgame/service/BaseBallGameService.java
> +        if(information.getStrikeCount() > 0) {
0의 의미는 뭘까요? 
상수 추출해주세요~

참고: 의미가 불분명한 매직 넘버를 상수로 선언하라
https://javabom.tistory.com/28

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/baseballgame/service/BaseBallGameService.java
> +        }
들여쓰기는 1depth로 유지 해주세요. 만약 2 depth 이상일 경우 메서드 추출 권장 드립니다. 

참고: 객체 생활 체조 원칙 1번
https://devwooks.tistory.com/59

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/baseballgame/service/BaseBallGameService.java
> +    }
어떤 숫자를 세팅하는걸까요? 메서드명 고려해봐주세요~

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/baseballgame/domain/Information.java
> +public class Information {
Information은 어떤 클래스일까요?
의미가 명확하면 좋을 듯 해요~

클린코드 : 의미 있게 구분하라(불용어-noise word-를 쓰지 말자) 
https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20%EC%9D%98%EB%AF%B8%20%EC%9E%88%EB%8A%94%20%EC%9D%B4%EB%A6%84.md

2022-04-26 08:46 UTC, JoyDaheeCha commented on src/main/java/gibin/kwon/study/baseballgame/domain/Information.java
> +    int[] goalNumber;
List 대신 array를 사용하신 이유가 뭘까요?

2022-04-27 02:34 UTC, givinkwon commented on src/test/java/gibin/kwon/study/StduyTest.java
> +    @DisplayName("splitTest")
좋은 피드백 감사드립니다~ 위에 언급해주신 커밋 부분이랑 테스트 코드 이름 부분은 참고해서 자동차 과제에서 해볼게요!

2022-04-27 02:38 UTC, updown-90 approved these changes
다희님이 리뷰를 너무 잘 달아주셔서 제가 달게 없네요...ㅎㅎㅎ

2022-05-04 04:51 UTC, givinkwon commented on src/test/java/gibin/kwon/study/StduyTest.java
> +    //@CsvSource(value = {"1: true", "2: true", "3 : true", "4:false","5:false"}, delimiter = ':')
밑에 코드에서 명시적으로 나타내는게 나을 수도 있겠다는 생각을 얼핏했어요 ㅎㅎ..
좀 더 찾아보니 valueSource로 처리하는게 나을 수도 있겠네요..

2022-05-04 04:55 UTC, givinkwon commented on src/main/java/gibin/kwon/study/Stduy.java
> +}
용도가 없어 삭제했습니다.

2022-05-04 04:57 UTC, givinkwon commented on src/main/java/gibin/kwon/study/baseballgame/controller/Controller.java
> +public class Controller {
뷰를 만드려다가 alert으로 처리하면서 view를 안만듬 + 객체로 관리하려다가 단순화하려고 함
=> MVC 구조로 잡아놓고 MVC로 안만들어서 혼동
이 발생한 것 같습니다 ㅠㅠ..

2022-05-04 04:58 UTC, givinkwon commented on src/main/java/gibin/kwon/study/StudyApplication.java
> +@SpringBootApplication
위와 같습니다.. 깊게 고민 않고 Springboot로 시작한 것 같네요.. 코멘트 감사합니다.

2022-05-04 05:01 UTC, givinkwon commented on src/main/java/gibin/kwon/study/baseballgame/service/BaseBallGameService.java
> +    final int END_NUMBER = 9;
해당 부분 크게 신경 쓰지 못했네용 ㅎㅎ
감사합니다.

2022-05-04 05:03 UTC, givinkwon commented on src/main/java/gibin/kwon/study/baseballgame/service/BaseBallGameService.java
> +        }
작성하다가 타협했는데
다시 분쟁 일으켜보겠습니다ㅎㅎ

2026-01-26 11:55 UTC, closed without merging